### ISSUE TITLE
COG not reported

### ISSUE THREAD

**Issue by dvnicolasdh** [Telicent-io/ies-code#5]
Please correct line 70 of: ies_track.py
cog = ies.addMeasure(iesGraph=iesGraph,measureClass=measures["cogClass"],value=sogVal,uom=measures["degTN"])

should read:
cog = ies.addMeasure(iesGraph=iesGraph,measureClass=measures["cogClass"],value=cogVal,uom=measures["degTN"])

**Comment by MonkeyChap** [comment]
Fixed - well spotted !
